### ISSUE TITLE
Can't access Baidu Dataset

### ISSUE THREAD

**Issue by ndgnuh** [HYOJINPARK/ExtPortraitSeg#2]
Hi, can you re-load the Baidu dataset on somewhere like Google Drive, Dropbox...? Baidu site keep making me download some weird apps when I download the dataset. Thank you.

**Comment by HYOJINPARK** [comment]
Hi @ndgnuh 
Thanks for your interest.
Yeah... it is really hard to use the Baidu site.....
To be honest, my co-author's friend helped us to download it.

Therefore I don't have the original Baidu dataset but only have our re-generated portrait dataset from Baidu.
I am sorry that I cannot help you....

**Comment by ndgnuh** [comment]
No worries, thank you very much!
